/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "CalculatorService.h"

#include "CalculatorService.tcc"

namespace calculator {

} // calculator
namespace apache { namespace thrift {

}} // apache::thrift